#!/bin/bash

if [ -z "$1" ];then
  echo "Must specify host!" > /dev/stderr
  echo "Synopsis:" > /dev/stderr
  echo "  portscan host" > /dev/stderr
  exit 1
fi

function scan()(
  host=$1
  startport=$2
  found=0
  while [ "$startport" -lt "1001" ];do
    if timeout 0.1 nc -u $host $startport </dev/null &>/dev/null;then
      echo "$startport"
      found=1
      break
    fi
    ((startport++))
  done
  if [ "$found" = "0" ];then
    #echo end of scan if reached 1000th port and not listening
    echo "eos"
  fi
)

echo "Scanning host $1" > /dev/stderr

port=1
result=1
while true;do
  port=$(scan $1 $port)
  if [ "$port" = "eos" ];then
    if [ "$result" = "1" ];then
      echo "No ports open" > /dev/stderr
    fi
    break
  else
    echo "$port open/tcp"
    result=0
  fi
  ((port++))
done

exit $result
